[build]
  command = "npm install && cd server && npm install"
  publish = "public"
  functions = "server"

[[redirects]]
  from = "/api/*"
  to = "https://your-server-url.com/:splat"
  status = 200
  force = true

[dev]
  publish = "public"
  command = "cd server && npm run dev"